//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soporte_averias.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SOPORTEEntities : DbContext
    {
        public SOPORTEEntities()
            : base("name=SOPORTEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Caso> TBL_Caso { get; set; }
        public virtual DbSet<TBL_Cliente> TBL_Cliente { get; set; }
        public virtual DbSet<TBL_DescripcionCaso> TBL_DescripcionCaso { get; set; }
        public virtual DbSet<TBL_Empleado> TBL_Empleado { get; set; }
        public virtual DbSet<TBL_EstadoCaso> TBL_EstadoCaso { get; set; }
        public virtual DbSet<TBL_FechaCierreCaso> TBL_FechaCierreCaso { get; set; }
        public virtual DbSet<TBL_FechaCreacionCaso> TBL_FechaCreacionCaso { get; set; }
        public virtual DbSet<TBL_Municipalidad> TBL_Municipalidad { get; set; }
        public virtual DbSet<TBL_PeriodoGarantia> TBL_PeriodoGarantia { get; set; }
        public virtual DbSet<TBL_PrioridadCaso> TBL_PrioridadCaso { get; set; }
        public virtual DbSet<TBL_Producto> TBL_Producto { get; set; }
        public virtual DbSet<TBL_Rol> TBL_Rol { get; set; }
        public virtual DbSet<TBL_Usuario> TBL_Usuario { get; set; }
    
        public virtual int sp_RegistrarUsuario(Nullable<int> cedula, string nombre, string apellido1, string apellido2, Nullable<int> telefono, string correo, string clave, ObjectParameter registrado, ObjectParameter mensaje)
        {
            var cedulaParameter = cedula.HasValue ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarUsuario", cedulaParameter, nombreParameter, apellido1Parameter, apellido2Parameter, telefonoParameter, correoParameter, claveParameter, registrado, mensaje);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ValidarUsuario(string correo, string clave)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ValidarUsuario", correoParameter, claveParameter);
        }
    }
}
