//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soporte_averias.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class TBL_Caso
    {
        public int TN_IdCaso { get; set; }

        [Required(ErrorMessage ="El periodo de garantía es obligatorio")]
        public Nullable<int> TN_IdPeriodoGarantia { get; set; }

		[Required(ErrorMessage = "La fecha de creación de caso es obligatoria")]
		public Nullable<int> TN_IdFechaCreacionCaso { get; set; }

		[Required(ErrorMessage = "El empleado es obligatorio")]
		public Nullable<int> TN_IdEmpleado { get; set; }

		[Required(ErrorMessage = "La municipalidad es obligatoria")]
		public Nullable<int> TN_IdMunicipalidad { get; set; }

		[Required(ErrorMessage = "El cliente es obligatorio")]
		public Nullable<int> TN_IdCliente { get; set; }

		[Required(ErrorMessage = "El producto es obligatorio")]
		public Nullable<int> TN_IdProducto { get; set; }

		[Required(ErrorMessage = "La descripción del caso es obligatoria")]
		public Nullable<int> TN_IdDescripcionCaso { get; set; }

		[Required(ErrorMessage = "La prioridad del caso es obligatoria")]
		public Nullable<int> TN_IdPrioridadCaso { get; set; }

		[Required(ErrorMessage = "El estado del caso es obligatorio")]
		public Nullable<int> TN_IdEstadoCaso { get; set; }

		[Required(ErrorMessage = "La fecha de cierre de caso es obligatoria")]
		public Nullable<int> TN_IdFechaCierreCaso { get; set; }

		[Required(ErrorMessage = "El usuario es obligatorio")]
		public Nullable<int> TN_IdUsuario { get; set; }
    
        public virtual TBL_Cliente TBL_Cliente { get; set; }
        public virtual TBL_DescripcionCaso TBL_DescripcionCaso { get; set; }
        public virtual TBL_Empleado TBL_Empleado { get; set; }
        public virtual TBL_EstadoCaso TBL_EstadoCaso { get; set; }
        public virtual TBL_FechaCierreCaso TBL_FechaCierreCaso { get; set; }
        public virtual TBL_FechaCreacionCaso TBL_FechaCreacionCaso { get; set; }
        public virtual TBL_Municipalidad TBL_Municipalidad { get; set; }
        public virtual TBL_PeriodoGarantia TBL_PeriodoGarantia { get; set; }
        public virtual TBL_PrioridadCaso TBL_PrioridadCaso { get; set; }
        public virtual TBL_Producto TBL_Producto { get; set; }
        public virtual TBL_Usuario TBL_Usuario { get; set; }
    }
}
