//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soporte_averias.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class TBL_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Usuario()
        {
            this.TBL_Caso = new HashSet<TBL_Caso>();
        }
    
        public int TN_IdUsuario { get; set; }
        public int TN_IdRol { get; set; }

        [Required(ErrorMessage ="La cédula es obligatoria")]
        public Nullable<int> TN_Cedula { get; set; }

		[Required(ErrorMessage = "El nombre es obligatorio")]
		public string TC_Nombre { get; set; }

		[Required(ErrorMessage = "El primer apellido es obligatorio")]
		public string TC_PrimerApellido { get; set; }

		[Required(ErrorMessage = "El segundo apellido es obligatorio")]
		public string TC_SegundoApellido { get; set; }

		[Required(ErrorMessage = "El correo es obligatorio")]
		public string TC_Correo { get; set; }

		[Required(ErrorMessage = "El teléfono es obligatorio")]
		public Nullable<int> TN_Telefono { get; set; }

		[Required(ErrorMessage = "La contraseña es obligatoria")]
		public string TC_Clave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Caso> TBL_Caso { get; set; }
        public virtual TBL_Rol TBL_Rol { get; set; }
    }
}
