//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soporte_averias.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class TBL_Rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Rol()
        {
            this.TBL_Usuario = new HashSet<TBL_Usuario>();
        }
    
        public int TN_IdRol { get; set; }
    
        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string TC_Nombre { get; set; }

        [Required(ErrorMessage = "La descripción es obligatoria")]
		public string TC_Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Usuario> TBL_Usuario { get; set; }
    }
}
